### ISSUE TITLE
Image is immediately cropped to aspect ratio

### ISSUE THREAD

**Issue by haidarcorp** [xclud/flutter_crop#23] opened 2020-07-16 11:35 UTC
Whenever I get the image and place it as the child of Crop, it is immediately cropped to the aspect ratio passed to the controller. How do i get the initial image to maintain its original aspect ratio while still cropping it to another aspect ratio in the crop view?

**Comment by haidarcorp** [comment] 2020-07-16 11:46
I saw some of the closed requests and removing fit: BoxFit.fitWidth fixes this. The problem, as someone else mentioned, is that instead of auto centering and fitting the width, it will just have chunks of transparency on the sides to fit the aspect ratio. Hopefully you can get around to fixing this because that's definitely the only thing preventing me from using this.

**Comment by xclud** [comment] 2020-07-16 18:26
@haidarcorp I didn't understand the problem. Can you attach a picture/video and write the steps to reproduce the problem ?

**Comment by LHDi** [comment] 2020-08-24 09:44
I think the same issue is tracked in #27.

**Comment by xclud** [comment] 2020-08-24 18:59
@LHDi Thanks for reporting. Still i am not able to reproduce this bug.

**Comment by LHDi** [comment] 2020-08-25 12:27
@xclud I am going to walk you through one of the scenarios (The one that I have):
I want the user to be able to change his profile picture, So I have created a dialog Widget for that.
First thing first I want the profile picture to have an aspect ratio of **1:1** (squared).
The dialog that I've created allows the user to select the source of the photo (either The Gallery or The Camera) and then select the picture (from the gallery) or take one (with the camera).
After the image was picked I render it inside the `Crop` to enable the user to crop it (obviously).

### The problem here is:
**I am not guaranteed that the user is going to pick an image with `1:1` (in our case) aspect ratio**
let's say that the user selected an image with an aspect ratio of `16:9` (landscape).
since the aspect ratios are not equal (`1:1` for the `Crop` widget and `16:9` for the user's image) we have to fit the image inside the `Crop` Widget, and for this, there are two options.

### 1- use `fit: BoxFit.cover`:
"_As small as possible while still covering the entire target box._" **Flutter documentation**
![](https://flutter.github.io/assets-for-api-docs/assets/painting/box_fit_cover.png)

as you can see when using the `cover` option we only render a part of the image inside the `Crop` widget and the other part (I'm gonna call it the **overflow** inspired by CSS ^_^) is gone you can't crop it in my case the user gets only the center square of his image.

So here we have a lost data (the **Overflow** is lost) we can overcome this problem by using the other option.
### 2- use `fit: BoxFit.contain`:
"_As large as possible while still containing the source entirely within the target box._" **Flutter documentation**
![](https://flutter.github.io/assets-for-api-docs/assets/painting/box_fit_contain.png)

here all the image is visible but there are some undesired parts. so here there is an added data (the blank parts at the edges).
And the user can select those parts and crop them (we don't want that).

**The desired behavior** is between those two, No lost parts nor added parts only the image.

_if this still not clear I can provide a code for it._

**Great package by the way**
Thank you!

**Comment by xclud** [comment] 2020-08-30 17:35
@LHDi thank you for description. I'd appreciate if you provide a [not] working code for this. e.g. link to a github repo.

**Comment by vemarav** [comment] 2020-10-16 10:32
<div align="center">
@xclud Using portrait images leads to this problem. user cannot pan image. I have set `3.5/2.3` aspectRatio for controller.
</div>
<br/>

<div align="center">

orginal image | image in crop widget
---|---
<img width="300" src="https://user-images.githubusercontent.com/17309962/96247820-41fe6900-0fc8-11eb-98b1-b09bd627ea4e.png" alt="original image" /> | <img width="300" src="https://user-images.githubusercontent.com/17309962/96247801-3c088800-0fc8-11eb-80d0-6c957607db6c.png" alt="after selected in crop"/>

</div>

**Comment by xclud** [comment] 2020-11-25 17:20
I close this issue for #27. Please feel free to continue this discussion there.

**Closed by xclud** 2020-11-25 17:20 UTC
